# نفس اسم الـ Worker الحالي على Cloudflare
name = "winter-term-cb93"
main = "src/index.ts"
compatibility_date = "2024-08-01"

[[d1_databases]]
binding = "DB"
database_name = "basateen"
database_id = "d7716e75-85ff-4927-9c59-052240793cab"

[vars]
ENVIRONMENT = "production"
